config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources :movies
  resources :series
  resources :documentary_films
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
  end
  

app/models/serie.rb
class Serie < ApplicationRecord
end

app/models/series.rb
class Series < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
    # Mostrar una lista de todos los documentales
    def index
      @documentary_films = DocumentaryFilm.all
    end
  
    # Nuevo objeto de documental para formularios
    def new
      @documentary_film = DocumentaryFilm.new
    end
  
    # Crear un nuevo documental
    def create
      @documentary_film = DocumentaryFilm.new(documentary_film_params)
      if @documentary_film.save
        redirect_to documentary_films_path
      else
        render :new
      end
    end
  
    private
  
    # Parámetros seguros para el documental
    def documentary_film_params
      params.require(:documentary_film).permit(:name, :synopsis, :director) 
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
      @movies = Movie.all
    end
  
    def new
      @movie = Movie.new
    end
  
    def create
      @movie = Movie.new(movie_params)
      if @movie.save
        redirect_to movies_path
      else
        render :new
      end
    end
  
    private
  
    def movie_params
      params.require(:movie).permit(:name, :synopsis, :director)
    end
  end
  

app/controllers/series_controller.rb
class SeriesController < ApplicationController
    # Mostrar una lista de todas las series
    def index
      @series = Series.all
    end
  
    # Nuevo objeto serie para formularios
    def new
      @serie = Series.new
    end
  
    # Crear una nueva serie
    def create
      @serie = Series.new(series_params)
      if @serie.save
        redirect_to series_path(@serie) 
      else
        render :new
      end
    end
  
    private
  
    # Parámetros seguros para la serie
    def series_params
      params.require(:series).permit(:name, :synopsis, :director) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/index.html.erb
<h1>Documentary Films List</h1>

<ul>
  <% @documentary_films.each do |doc_film| %>
    <li>
      <strong>Name:</strong> <%= doc_film.name %><br>
      <strong>Synopsis:</strong> <%= doc_film.synopsis %><br>
      <strong>Director:</strong> <%= doc_film.director %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add New Documentary Film', new_documentary_film_path %>

app/views/documentary_films/new.html.erb
<h1>Add New Documentary Film</h1>

<%= form_with model: @documentary_film, local: true do |form| %>
  <% if @documentary_film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@documentary_film.errors.count, "error") %> prohibited this documentary film from being saved:</h2>

      <ul>
      <% @documentary_film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Documentary Films List', documentary_films_path %>

app/views/home/index.html.erb
<h1>Bienvenido</h1>

<p>
  Selecciona una de las siguientes opciones:
</p>

<ul>
  <li><%= link_to "Películas", movies_path %></li>
  <li><%= link_to "Series", series_index_path %></li>
  <li><%= link_to "Documentales", documentary_films_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Movies List</h1>

<ul>
  <% @movies.each do |movie| %>
    <li>
      <strong>Name:</strong> <%= movie.name %><br>
      <strong>Synopsis:</strong> <%= movie.synopsis %><br>
      <strong>Director:</strong> <%= movie.director %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>Add New Movie</h1>

<%= form_with model: @movie, local: true do |form| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Movies List', movies_path %>

app/views/series/index.html.erb
<h1>Series List</h1>

<ul>
  <% @series.each do |serie| %>
    <li>
      <strong>Name:</strong> <%= serie.name %><br>
      <strong>Synopsis:</strong> <%= serie.synopsis %><br>
      <strong>Director:</strong> <%= serie.director %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add New Series', new_series_path %>

app/views/series/new.html.erb
<h1>Add New Series</h1>

<%= form_with model: @serie, local: true do |form| %>
  <% if @serie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@serie.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @serie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Series List', series_index_path %>